name: Bug report
description: Create a report to help us address issues you are facing
title: "[Bug] "
labels: [bug]
body:
  - type: checkboxes
    id: duplication
    attributes:
      label: ⠀
      options:
        - label: This issue is not duplicated with any other open or closed issues
          required: true

  - type: checkboxes
    id: answer
    attributes:
      label: ⠀
      options:
        - label: Already read Q&A
          required: true

  - type: markdown
    attributes:
      value: |
        ⠀
        Thanks for taking the time to make us better!

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: |
        App crashes on startup every time after changing settings.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: |
        App started normally, everything worked fine.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the bug
      placeholder: |
        1. Turn on "Re-calculate on startup" in "Experimental settings"
        2. Restart the app
        3. Crash
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Device information
      description: Provide details about your system environment
      placeholder: |
        Device:
        System:
        Version:
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: |
        modified_setting_items.jpg
        crashed_screen.jpg
    validations:
      required: false

  - type: textarea
    id: log
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem
      placeholder: |
        Android/data/fun.upup.musicfree/files/log/trace-log.log
    validations:
      required: false

  - type: textarea
    id: detail
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: |
        My microphone is broken
    validations:
      required: false
